# Generated by Django 5.2.8 on 2025-11-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
